_BASE_: "Base-Panoptic-PRFPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
#  WEIGHTS: "path/panoptic_r101_3x_fan/model_final.pth"
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000