_BASE_: "../Base-RCNN-PRFPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#  WEIGHTS: "path/faster_rcnn_r50_1x_prfpn/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
